### ISSUE TITLE
Parent Width Overflow

### ISSUE THREAD

**Issue by eportet** [Splact/react-occamy-text#3]
Thank you for this awesome package!

Just wanted to let you know of these behaviours I encountered while using it.
 - Shorter strings overflow the parent width
 - Strings with no spaces overflow the parent width

Is this expected behaviour? Is there a way to correct it?

I made a Codesandbox to showcase the issues.

[![Edit mzo50l47r8](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mzo50l47r8)

**Comment by Splact** [comment]
Thanks for the issue 👍!

The problem here is that Occamy checks only for height overflow. I'll try to fix this during next days (probably during the weekend).

**Comment by Splact** [comment]
This is solved in v1.1.3 👍🏻
